name: aris_ussd
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  bubble_bottom_bar: ^1.2.0
  curved_navigation_bar: ^0.3.7
  url_launcher: ^5.7.10
  carousel_slider: ^3.0.0
  smooth_page_indicator: ^0.2.0
  webview_flutter: ^1.0.7
  share: ^0.6.5+4
  draggable_floating_button: ^0.1.1
  image_picker: ^0.6.7+22
  firebase_messaging:
  dio: ^3.0.10
  path_provider: ^1.6.27
  archive: ^2.0.13
  shared_preferences: ^0.5.12+4
  flutter_email_sender: ^5.0.2
  ussd: ^0.0.2+1
  flashy_tab_bar: ^0.0.3
  bottom_navy_bar: ^6.0.0
  flutter_google_ad_manager: ^0.11.1
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/beeline/bback.jpeg
    - assets/images/beeline/bwidget.jpg
    - assets/images/beeline/beelogo.png
    - assets/images/pack/call.png
    - assets/images/pack/net.png
    - assets/images/pack/news.png
    - assets/images/pack/plan.png
    - assets/images/pack/sms.png
    - assets/images/pack/ussd.png
    - assets/images/ucell/ucell.jpg
    - assets/images/mobi/mobi.png
    - assets/images/uzmob/uzmob.png
    - assets/images/uzmob/uzmobback.jpg
    - assets/images/operator.png
    - assets/images/social/call-min.png
    - assets/images/social/fb-min.png
    - assets/images/social/ins-min.png
    - assets/images/social/tg-min.png
    - assets/images/social/sendmail.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
